INSERT INTO game(start_date) VALUES (null);

INSERT INTO team(name, score, game_id) VALUES
    ('Gryffindor', 0, 1),
    ('Slytherin', 0, 1),
    ('Hufflepuff', 0, 1),
    ('Ravenclaw', 0, 1);

INSERT INTO player(name, team_id, hash) VALUES
    ('Harry Potter', 1, '1'),
    ('Hermione Granger', 1, '2'),
    ('Ronald Weasley', 1, '3'),
    ('Oliver Wood', 1, '4'),

    ('Gregory Goyle', 2, '5'),
    ('Vincent Crabbe', 2, '6'),
    ('Draco Lucius Malfoy', 2, '7'),

    ('Cedric Diggory', 3, '8'),
    ('Justin Finch-Fletchley', 3, '9'),

    ('Luna Lovegood', 4, '10');



INSERT INTO game(start_date) VALUES (null);

INSERT INTO team(name, score, game_id) VALUES
    ('Gryffindor', 0, 2),
    ('Slytherin', 0, 2),
    ('Hufflepuff', 0, 2);

INSERT INTO player(name, team_id, hash) VALUES
    ('Harry Potter', 5, '1'),
    ('Hermione Granger', 5, '2'),
    ('Ronald Weasley', 5, '3'),
    ('Oliver Wood', 5, '4'),

    ('Gregory Goyle', 6, '5'),
    ('Vincent Crabbe', 6, '6'),
    ('Draco Lucius Malfoy', 6, '7'),

    ('Cedric Diggory', 7, '8'),
    ('Justin Finch-Fletchley', 7, '9');



INSERT INTO game(start_date) VALUES (null);

INSERT INTO team(name, score, game_id) VALUES
    ('Gryffindor', 0, 3),
    ('Slytherin', 0, 3);

INSERT INTO player(name, team_id, hash) VALUES
    ('Harry Potter', 8, '1'),
    ('Hermione Granger', 8, '2'),
    ('Ronald Weasley', 8, '3'),
    ('Oliver Wood', 8, '4'),

    ('Gregory Goyle', 9, '5'),
    ('Vincent Crabbe', 9, '6'),
    ('Draco Lucius Malfoy', 9, '7');

INSERT INTO word(word) VALUES
    ('Accio'),
    ('Acid pops'),
    ('Aconite'),
    ('Acromantula'),
    ('Alchemy'),
    ('Alohomora'),
    ('Animagus'),
    ('Anti-venom'),
    ('Aparecium'),
    ('Apparate'),
    ('Arithmancy'),
    ('Astronomy'),
    ('Auror'),
    ('Azkaban'),
    ('Basilisk'),
    ('Bat-Bogey Hex'),
    ('Beater'),
    ('Beauxbatons Academy of Magic'),
    ('Bertie Bott''s Every Flavour Beans'),
    ('Bezoar'),
    ('Black Forest'),
    ('Blast-Ended Skrewt'),
    ('Blood Blisterpod'),
    ('Blood-flavoured lollipops'),
    ('Bludgers'),
    ('Body-Bind curse'),
    ('Boggart'),
    ('Borgin and Burkes'),
    ('Bouncing Bulb'),
    ('Bowtruckle'),
    ('Broomstick Servicing Kit'),
    ('Bubble-Head Charm'),
    ('Bubotuber'),
    ('Bulbadox powder'),
    ('Burrow'),
    ('Butterbeer'),
    ('Canary Creams'),
    ('Care of Magical Creatures'),
    ('Centaurs'),
    ('Chamber of Secrets'),
    ('Charm'),
    ('Chaser'),
    ('Chimaera'),
    ('Chocoballs'),
    ('Chocolate Frogs'),
    ('Chudley Cannons'),
    ('Cleansweep Eleven'),
    ('Cleansweep Seven'),
    ('Cockroach Clusters'),
    ('Colloportus'),
    ('Come and Go Room'),
    ('Comet'),
    ('Common room'),
    ('Common Welsh Green'),
    ('Cornish pixies'),
    ('Cribbages Wizarding Crackers'),
    ('Cruciatus Curse'),
    ('Crumple-Horned Snorkacks'),
    ('Crup'),
    ('Daily Prophet'),
    ('Dark detectors'),
    ('Dark Mark'),
    ('Death Eaters'),
    ('Deathday Party'),
    ('Decree'),
    ('Defence Against the Dark Arts'),
    ('Deflating Draught'),
    ('Dementor'),
    ('Dementor''s Kiss'),
    ('Densaugeo'),
    ('Dervish and Banges'),
    ('Devil''s Snare'),
    ('Diagon Alley'),
    ('Diffindo'),
    ('Disapparate'),
    ('Disillusionment Charm'),
    ('Dissendium'),
    ('Divination'),
    ('Doxy'),
    ('Dr Filibuster''s Fabulous Wet-Start, No-Heat Fireworks'),
    ('Dr Ubbly''s Oblivious Unction'),
    ('Draco Dormiens Nunquam Titillandus'),
    ('Dragon'),
    ('Draught of Living Death'),
    ('Draught of Peace'),
    ('Drooble''s Best Blowing Gum'),
    ('Duelling Club'),
    ('Dumbledore''s Army'),
    ('Dungbomb'),
    ('Durmstrang Institute'),
    ('Eeylops Owl Emporium'),
    ('Elixir of Life'),
    ('Engorgio'),
    ('Evanesco'),
    ('Expecto patronum'),
    ('Expelliarmus'),
    ('Exploding bonbons'),
    ('Exploding Snap'),
    ('Extendable Ears'),
    ('Fainting Fancy'),
    ('Ferula'),
    ('Fidelius Charm'),
    ('Finite Incantatem'),
    ('Firebolt'),
    ('Fizzing Whizzbee'),
    ('Fizzing Whizzbees'),
    ('Flagrate'),
    ('Flobberworm'),
    ('Floo Network'),
    ('Floo powder'),
    ('Florean Fortesque''s Ice-Cream Parlour'),
    ('Flourish and Blotts'),
    ('Flutterby Bush'),
    ('Foe-Glass'),
    ('Forbidden Forest'),
    ('Ford Anglia'),
    ('Fountain of Magical Brethren'),
    ('Four-Point Spell'),
    ('Fudge Flies'),
    ('Furnunculus'),
    ('Galleon'),
    ('Gambol and Japes Wizarding Joke Shop'),
    ('Garrotting Gas'),
    ('Ghoul'),
    ('Giant'),
    ('Gillyweed'),
    ('Gnomes'),
    ('Goblet of Fire'),
    ('Goblins'),
    ('Gobstones'),
    ('Godric''s Hollow'),
    ('Golden Snitch'),
    ('Great Hall'),
    ('Grim'),
    ('Grimmauld Place'),
    ('Grindylow'),
    ('Gringotts'),
    ('Grunnings'),
    ('Gryffindor house'),
    ('Gubraithian fire'),
    ('Gurg'),
    ('Half-breed'),
    ('Hand of Glory'),
    ('Headless Hat'),
    ('Headless Hunt'),
    ('Healer'),
    ('Hebridean Black'),
    ('Heir of Slytherin'),
    ('Heliopath'),
    ('Hellebore'),
    ('Heptomology'),
    ('Herbology'),
    ('Hinkypunk'),
    ('Hippogriff'),
    ('Hit Wizards'),
    ('Hogsmeade'),
    ('Hogwarts School of Witchcraft and Wizardry'),
    ('Honeydukes'),
    ('House Cup'),
    ('House-elf'),
    ('Howler'),
    ('Hufflepuff house'),
    ('Ice Mice'),
    ('Impediment Jinx'),
    ('Imperius Curse'),
    ('Imperturbable Charm'),
    ('Impervius'),
    ('Incarcerous'),
    ('Incendio'),
    ('Inquisitorial Squad'),
    ('Inter-departmental memos'),
    ('Invisibility Cloak'),
    ('Jelly Slugs'),
    ('Jelly-Legs Jinx'),
    ('Kappa'),
    ('Karkus'),
    ('Keeper'),
    ('Killing Curse'),
    ('King''s Cross Station'),
    ('Knarl'),
    ('Kneazle'),
    ('Knight Bus'),
    ('Knockturn Alley'),
    ('Knut'),
    ('Kwikspell'),
    ('Leaky Cauldron'),
    ('Legilimency'),
    ('Legilimens'),
    ('Legilimens'),
    ('Leprechaun'),
    ('Locomotor'),
    ('Lumos'),
    ('Madam Malkin''s Robes for All Occassions'),
    ('Magical eye'),
    ('Magical Law Enforcement Squad'),
    ('Magical Menagerie'),
    ('Magorian'),
    ('Mandragora'),
    ('Mandrake'),
    ('Marauder''s Map'),
    ('Merpeople'),
    ('Metamorphmagus'),
    ('Mimbulus mimbletonia'),
    ('Ministry of Magic'),
    ('Mirror of Erised'),
    ('Mobiliarbus'),
    ('Mobilicorpus'),
    ('Monkshood'),
    ('Morsmordre'),
    ('Mudblood'),
    ('Muggle'),
    ('Muggle duelling'),
    ('Muggle Studies'),
    ('Murtlap'),
    ('Murtlap essence'),
    ('Nargles'),
    ('N.E.W.T.s'),
    ('Niffler'),
    ('Nimbus Two Thousand'),
    ('Nimbus Two Thousand and One'),
    ('Norwegian Ridgeback'),
    ('Nosebleed Nougat'),
    ('Nox'),
    ('Obliviate'),
    ('Obliviator'),
    ('Occlumency'),
    ('Ollivanders'),
    ('Omnioculars'),
    ('Order of the Phoenix'),
    ('Ornithomancy'),
    ('O.W.L.s'),
    ('Parselmouth'),
    ('Parseltongue'),
    ('Patronus'),
    ('Pensieve'),
    ('Pepper Imps'),
    ('Pepperup Potion'),
    ('Peppermint Toads'),
    ('Petrificus Totalus'),
    ('Philosopher''s Stone'),
    ('Phoenix'),
    ('Platform nine and three-quarters'),
    ('Pocket Sneakoscope'),
    ('Poltergeist'),
    ('Polyjuice Potion'),
    ('Porlock'),
    ('Portkey'),
    ('Portus'),
    ('Potions'),
    ('Prior Incantato'),
    ('Privet Drive'),
    ('Protego'),
    ('Puking Pastilles'),
    ('Pumpkin juice'),
    ('Pumpkin pasty'),
    ('Purge & Dowse Ltd.'),
    ('Put-Outer'),
    ('Quaffle'),
    ('Quality Quidditch Supplies'),
    ('Quick-Quotes Quill'),
    ('Quidditch'),
    ('Quietus'),
    ('Ravenclaw house'),
    ('Red Cap'),
    ('Reducio'),
    ('Reductor Curse'),
    ('Relashio'),
    ('Remembrall'),
    ('Rennervate'),
    ('Reparo'),
    ('Rictusempra'),
    ('Riddikulus'),
    ('Riddle House'),
    ('Room of Requirement'),
    ('Salamander'),
    ('Scourgify'),
    ('Scrivenshaft''s Quill Shop'),
    ('Secrecy Sensor'),
    ('Secret Keeper'),
    ('Seeing Eye'),
    ('Seeker'),
    ('Seer'),
    ('Self-shuffling playing cards'),
    ('Shield Charm'),
    ('Shrieking Shack'),
    ('Sickle'),
    ('Silencio'),
    ('Skele-Gro'),
    ('Skiving Snackboxes'),
    ('Sleekeazy''s Hair Potion'),
    ('Sloth Grip Roll'),
    ('Slytherin house'),
    ('Smeltings'),
    ('Sneakoscope'),
    ('Sonorus'),
    ('Sorting Hat'),
    ('Spellotape'),
    ('S.P.E.W.'),
    ('Splinching'),
    ('Squib'),
    ('Stealth Sensoring Spell'),
    ('Stupefy'),
    ('Sunday Prophet'),
    ('Swelling Solution'),
    ('Tarantallegra'),
    ('Thestral'),
    ('Three Broomsticks'),
    ('Time-Turner'),
    ('Ton-Tongue Toffee'),
    ('Toothflossing Stringmints'),
    ('Toujours pur'),
    ('Transfiguration'),
    ('Triwizard Tournament'),
    ('Two-way mirrors'),
    ('Umbridge-itis'),
    ('Unforgivable Curses'),
    ('Unicorn'),
    ('Unspeakable'),
    ('Vampire'),
    ('Venomous Tentacula seeds'),
    ('Veritaserum'),
    ('Wand'),
    ('Wand-tree'),
    ('Wartcap powder'),
    ('Watchwizard'),
    ('Weasleys'' Wildfire Whiz-bangs'),
    ('Weasleys'' Wizarding Wheezes'),
    ('Weird Sisters'),
    ('Welcomewitch'),
    ('Werewolf'),
    ('Whomping Willow'),
    ('Wingardium Leviosa'),
    ('Wizarding Examinations Authority'),
    ('Wizengamot'),
    ('Wizengamot Administration Services'),
    ('Wolfsbane');
